"""horario de clases

Revision ID: 6343b2655c8e
Revises: afc14d85d246
Create Date: 2026-07-20 17:27:07.882816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6343b2655c8e'
down_revision: Union[str, Sequence[str], None] = 'afc14d85d246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semestre_horario',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('numero')
    )
    op.create_table('clase_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_numero', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('hora_fin', sa.Integer(), nullable=False),
    sa.Column('materia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['semestre_numero'], ['semestre_horario.numero'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clase_horario')
    op.drop_table('semestre_horario')
    # ### end Alembic commands ###
