"""actividades

Revision ID: e7b5f82c9ee7
Revises: 6343b2655c8e
Create Date: 2026-07-21 20:46:47.335681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7b5f82c9ee7'
down_revision: Union[str, Sequence[str], None] = '6343b2655c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.Column('modo_entrega', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad')
    # ### end Alembic commands ###
