// Datos del plan de estudios — Ingeniería Mecánica
// Cada curso: id único, código, nombre, créditos, ciclo (tec/ing),
// semestre, categoría (color), tipo (OB/OC/EI/EE/CP),
// aprobado (estado por defecto) y prereq (array de ids de cursos previos).
//
// Para añadir un prerrequisito: prereq: ["tec-1", "tec-9"]
const COURSES = [
    {
        "id": "tec-1",
        "name": "CÁLCULO DIFERENCIAL",
        "code": "1",
        "credits": 4.0,
        "cycle": "tec",
        "semester": 1,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-2",
        "name": "CÁTEDRA FRANCISCO JOSÉ DE CALDAS",
        "code": "4",
        "credits": 1.0,
        "cycle": "tec",
        "semester": 1,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-3",
        "name": "ÁLGEBRA LINEAL",
        "code": "9",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 1,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-4",
        "name": "PRODUCCIÓN Y COMPRENSIÓN DE TEXTOS I",
        "code": "1054",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 1,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-5",
        "name": "ÉTICA Y SOCIEDAD",
        "code": "1075",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 1,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-6",
        "name": "DIBUJO TÉCNICO",
        "code": "1411",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 1,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-7",
        "name": "INTRODUCCIÓN A LA MECÁNICA INDUSTRIAL",
        "code": "19701",
        "credits": 1.0,
        "cycle": "tec",
        "semester": 1,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-8",
        "name": "SEGUNDA LENGUA I - INGLÉS",
        "code": "9901",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 1,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-9",
        "name": "FÍSICA I: MECÁNICA NEWTONIANA",
        "code": "3",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 2,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-10",
        "name": "CÁLCULO INTEGRAL",
        "code": "7",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 2,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": ["tec-1"]
    },
    {
        "id": "tec-11",
        "name": "CÁTEDRA DEMOCRACIA Y CIUDADANÍA",
        "code": "12",
        "credits": 1.0,
        "cycle": "tec",
        "semester": 2,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-12",
        "name": "PRODUCCIÓN Y COMPRENSIÓN DE TEXTOS II",
        "code": "1056",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 2,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-13",
        "name": "MATERIALES METÁLICOS",
        "code": "19702",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 2,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-14",
        "name": "DIBUJO DE ELEMENTOS DE MÁQUINAS",
        "code": "19703",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 2,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-15",
        "name": "FUNDAMENTOS DE PROGRAMACIÓN",
        "code": "19704",
        "credits": 1.0,
        "cycle": "tec",
        "semester": 2,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-16",
        "name": "SEGUNDA LENGUA II - INGLÉS",
        "code": "9903",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 2,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-17",
        "name": "FÍSICA II: ELECTROMAGNETISMO",
        "code": "13",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 3,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-18",
        "name": "CIENCIA TECNOLOGÍA Y SOCIEDAD",
        "code": "1060",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 3,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-19",
        "name": "ESTATICA",
        "code": "1421",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 3,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-20",
        "name": "MATERIALES POLIMÉRICOS Y COMPUESTOS",
        "code": "19705",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 3,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-21",
        "name": "DIBUJO DE TALLER INDUSTRIAL",
        "code": "19706",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 3,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-22",
        "name": "METROLOGÍA DIMENSIONAL",
        "code": "19707",
        "credits": 1.0,
        "cycle": "tec",
        "semester": 3,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-23",
        "name": "SEGUNDA LENGUA III - INGLÉS",
        "code": "9903",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 3,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-24",
        "name": "PROCESOS DE MECANIZADO I",
        "code": "19708",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 3,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-25",
        "name": "CÁLCULO MULTIVARIADO",
        "code": "16",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 4,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-26",
        "name": "MECANICA DE FLUIDOS",
        "code": "1433",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 4,
        "category": "energias",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-27",
        "name": "RESISTENCIA DE MATERIALES",
        "code": "1436",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 4,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-28",
        "name": "PROCESOS DE MECANIZADO II",
        "code": "19709",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 4,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-29",
        "name": "DINÁMICA DE MECANISMOS",
        "code": "19710",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 4,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-30",
        "name": "FÍSICA III: ONDAS Y FÍSICA MODERNA",
        "code": "1428",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 4,
        "category": "fisica-matematica",
        "type": "CP",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-31",
        "name": "ECUACIONES DIFERENCIALES",
        "code": "88",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 5,
        "category": "fisica-matematica",
        "type": "CP",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-32",
        "name": "TERMODINÁMICA",
        "code": "1426",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 5,
        "category": "energias",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-33",
        "name": "MANTENIMIENTO DE MÁQUINAS",
        "code": "19711",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 5,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-34",
        "name": "PROCESOS DE CONFORMADO",
        "code": "19712",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 5,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-35",
        "name": "ELEMENTOS DE MÁQUINAS I",
        "code": "19713",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 5,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-36",
        "name": "ELECTIVA INTRISECA 1",
        "code": "-",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 5,
        "category": "electivas-grado",
        "type": "EI",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-37",
        "name": "ELECTIVA INTRISECA 2",
        "code": "-",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 5,
        "category": "electivas-grado",
        "type": "EI",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-38",
        "name": "TRABAJO DE GRADO TECNOLÓGICO",
        "code": "1446",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 6,
        "category": "electivas-grado",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-39",
        "name": "DISEÑO DE PROCESOS DE FABRICACIÓN",
        "code": "19714",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 6,
        "category": "fabricacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-40",
        "name": "ELEMENTOS DE MÁQUINAS II",
        "code": "19715",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 6,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-41",
        "name": "MÁQUINAS ELÉCTRICAS",
        "code": "19716",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 6,
        "category": "energias",
        "type": "OB",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-42",
        "name": "MÁQUINAS HIDRÁULICAS",
        "code": "1824",
        "credits": 3.0,
        "cycle": "tec",
        "semester": 6,
        "category": "energias",
        "type": "CP",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-43",
        "name": "ELECTIVA INTRISECA 3",
        "code": "-",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 6,
        "category": "electivas-grado",
        "type": "EI",
        "approved": true,
        "prereq": []
    },
    {
        "id": "tec-44",
        "name": "ELECTIVA EXTRINSECA",
        "code": "-",
        "credits": 2.0,
        "cycle": "tec",
        "semester": 6,
        "category": "electivas-grado",
        "type": "EE",
        "approved": true,
        "prereq": []
    },
    {
        "id": "ing-1",
        "name": "PROBABILIDAD Y ESTADÍSTICA",
        "code": "19801",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 7,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-2",
        "name": "TERMODINÁMICA APLICADA",
        "code": "19804",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 7,
        "category": "energias",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-3",
        "name": "DISEÑO POR ELEMENTOS FINITOS",
        "code": "1817",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 7,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-4",
        "name": "ASEGURAMIENTO METROLÓGICO",
        "code": "19802",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 7,
        "category": "fabricacion",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-5",
        "name": "CÁTEDRA DE CONTEXTO",
        "code": "1082",
        "credits": 1.0,
        "cycle": "ing",
        "semester": 7,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-6",
        "name": "PRODUCCIÓN DE TEXTOS CIENTÍFICOS",
        "code": "19803",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 7,
        "category": "lenguaje-sociales",
        "type": "OC",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-7",
        "name": "DISEÑO EXPERIMENTAL",
        "code": "19806",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 8,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-8",
        "name": "TRANSFERENCIA DE CALOR",
        "code": "1818",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 8,
        "category": "energias",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-9",
        "name": "MANTENIMIENTO DE EQUIPOS INDUSTRIALES",
        "code": "19805",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 8,
        "category": "fisica-matematica",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-10",
        "name": "DISEÑO DE MÁQUINAS",
        "code": "1823",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 8,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-11",
        "name": "ELECTIVA EXTRÍNSECA",
        "code": "-",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 8,
        "category": "electivas-grado",
        "type": "EE",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-12",
        "name": "SISTEMAS DINÁMICOS Y CONTROL",
        "code": "1805",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 8,
        "category": "diseno-programacion",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-13",
        "name": "TRABAJO DE GRADO I",
        "code": "1670",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 9,
        "category": "electivas-grado",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-14",
        "name": "MÁQUINAS TÉRMICAS",
        "code": "1838",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 9,
        "category": "energias",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-15",
        "name": "INGENIERÍA ECONÓMICA",
        "code": "1619",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 9,
        "category": "lenguaje-sociales",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-16",
        "name": "ELECTIVA DE PROFUNDIZACIÓN I",
        "code": "-",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 9,
        "category": "electivas-grado",
        "type": "EI",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-17",
        "name": "ELECTIVA DE PROFUNDIZACIÓN III",
        "code": "-",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 9,
        "category": "electivas-grado",
        "type": "EI",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-18",
        "name": "INGENIERÍA DE MANUFACTURA",
        "code": "19807",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 9,
        "category": "fabricacion",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-19",
        "name": "ELECTIVA DE PROFUNDIZACIÓN II",
        "code": "-",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 9,
        "category": "electivas-grado",
        "type": "EI",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-20",
        "name": "TRABAJO DE GRADO II",
        "code": "1831",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 10,
        "category": "electivas-grado",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-21",
        "name": "ELECTIVA DE PROFUNDIZACIÓN V",
        "code": "-",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 10,
        "category": "electivas-grado",
        "type": "EI",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-22",
        "name": "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS",
        "code": "19808",
        "credits": 3.0,
        "cycle": "ing",
        "semester": 10,
        "category": "lenguaje-sociales",
        "type": "OB",
        "approved": false,
        "prereq": []
    },
    {
        "id": "ing-23",
        "name": "ELECTIVA DE PROFUNDIZACIÓN IV",
        "code": "-",
        "credits": 2.0,
        "cycle": "ing",
        "semester": 10,
        "category": "electivas-grado",
        "type": "EI",
        "approved": false,
        "prereq": []
    }
];
